// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parkingLots.sql

package database

import (
	"context"
)

const createParkingLot = `-- name: CreateParkingLot :one
INSERT INTO parkinglots(id, name, slots, occupiedslots)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    0
)
RETURNING id, name, slots, occupiedslots
`

type CreateParkingLotParams struct {
	Name  string
	Slots int32
}

func (q *Queries) CreateParkingLot(ctx context.Context, arg CreateParkingLotParams) (Parkinglot, error) {
	row := q.db.QueryRowContext(ctx, createParkingLot, arg.Name, arg.Slots)
	var i Parkinglot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.Occupiedslots,
	)
	return i, err
}

const getParkingLots = `-- name: GetParkingLots :many
SELECT id, name, slots, occupiedslots
FROM parkinglots
`

func (q *Queries) GetParkingLots(ctx context.Context) ([]Parkinglot, error) {
	rows, err := q.db.QueryContext(ctx, getParkingLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parkinglot
	for rows.Next() {
		var i Parkinglot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slots,
			&i.Occupiedslots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
