// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parkingLots.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createParkingLot = `-- name: CreateParkingLot :one
INSERT INTO parkinglots(id, name, slots, occupiedslots)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    0
)
RETURNING id, name, slots, occupiedslots
`

type CreateParkingLotParams struct {
	Name  string
	Slots int32
}

func (q *Queries) CreateParkingLot(ctx context.Context, arg CreateParkingLotParams) (Parkinglot, error) {
	row := q.db.QueryRowContext(ctx, createParkingLot, arg.Name, arg.Slots)
	var i Parkinglot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.Occupiedslots,
	)
	return i, err
}

const deleteParkingLot = `-- name: DeleteParkingLot :execresult
DELETE FROM parkinglots
WHERE id = $1
`

func (q *Queries) DeleteParkingLot(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteParkingLot, id)
}

const getParkingLotFromID = `-- name: GetParkingLotFromID :one
SELECT id, name, slots, occupiedslots
FROM parkinglots
WHERE id = $1
`

func (q *Queries) GetParkingLotFromID(ctx context.Context, id uuid.UUID) (Parkinglot, error) {
	row := q.db.QueryRowContext(ctx, getParkingLotFromID, id)
	var i Parkinglot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.Occupiedslots,
	)
	return i, err
}

const getParkingLots = `-- name: GetParkingLots :many
SELECT id, name, slots, occupiedslots
FROM parkinglots
`

func (q *Queries) GetParkingLots(ctx context.Context) ([]Parkinglot, error) {
	rows, err := q.db.QueryContext(ctx, getParkingLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parkinglot
	for rows.Next() {
		var i Parkinglot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slots,
			&i.Occupiedslots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOccupiedSlot = `-- name: UpdateOccupiedSlot :exec
UPDATE parkinglots
SET occupiedSlots = occupiedSlots + $1
WHERE id = $2
`

type UpdateOccupiedSlotParams struct {
	Occupiedslots int32
	ID            uuid.UUID
}

func (q *Queries) UpdateOccupiedSlot(ctx context.Context, arg UpdateOccupiedSlotParams) error {
	_, err := q.db.ExecContext(ctx, updateOccupiedSlot, arg.Occupiedslots, arg.ID)
	return err
}
