// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parkingLogs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLog = `-- name: CreateLog :one
INSERT INTO parking_logs(id, user_id, parking_lot_id, event_type, time)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
) RETURNING id, user_id, parking_lot_id, event_type, time
`

type CreateLogParams struct {
	UserID       uuid.UUID
	ParkingLotID uuid.UUID
	EventType    string
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (ParkingLog, error) {
	row := q.db.QueryRowContext(ctx, createLog, arg.UserID, arg.ParkingLotID, arg.EventType)
	var i ParkingLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParkingLotID,
		&i.EventType,
		&i.Time,
	)
	return i, err
}

const getLogs = `-- name: GetLogs :many
SELECT id, user_id, parking_lot_id, event_type, time FROM parking_logs
`

func (q *Queries) GetLogs(ctx context.Context) ([]ParkingLog, error) {
	rows, err := q.db.QueryContext(ctx, getLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParkingLog
	for rows.Next() {
		var i ParkingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParkingLotID,
			&i.EventType,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsFromUserID = `-- name: GetLogsFromUserID :many
SELECT id, user_id, parking_lot_id, event_type, time
FROM parking_logs
WHERE user_id = $1
`

func (q *Queries) GetLogsFromUserID(ctx context.Context, userID uuid.UUID) ([]ParkingLog, error) {
	rows, err := q.db.QueryContext(ctx, getLogsFromUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParkingLog
	for rows.Next() {
		var i ParkingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParkingLotID,
			&i.EventType,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
