// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parkingLots.sql

package database

import (
	"context"
)

const getParkingLots = `-- name: GetParkingLots :many
SELECT id, name, slots, occupiedslots
FROM parkinglots
`

func (q *Queries) GetParkingLots(ctx context.Context) ([]Parkinglot, error) {
	rows, err := q.db.QueryContext(ctx, getParkingLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parkinglot
	for rows.Next() {
		var i Parkinglot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slots,
			&i.Occupiedslots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
