// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews(user_id, parking_lot_id, title, description, score, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
) RETURNING user_id, parking_lot_id, title, description, score, created_at, updated_at
`

type CreateReviewParams struct {
	UserID       uuid.UUID
	ParkingLotID uuid.UUID
	Title        string
	Description  sql.NullString
	Score        int32
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.UserID,
		arg.ParkingLotID,
		arg.Title,
		arg.Description,
		arg.Score,
	)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.ParkingLotID,
		&i.Title,
		&i.Description,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT user_id, parking_lot_id, title, description, score, created_at, updated_at FROM reviews
WHERE user_id = $1 AND parking_lot_id = $2
`

type GetReviewByIDParams struct {
	UserID       uuid.UUID
	ParkingLotID uuid.UUID
}

func (q *Queries) GetReviewByID(ctx context.Context, arg GetReviewByIDParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, arg.UserID, arg.ParkingLotID)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.ParkingLotID,
		&i.Title,
		&i.Description,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews
SET 
title = $1,
description = $2,
score = $3,
updated_at = NOW()
WHERE user_id = $4 AND parking_lot_id = $5
`

type UpdateReviewParams struct {
	Title        string
	Description  sql.NullString
	Score        int32
	UserID       uuid.UUID
	ParkingLotID uuid.UUID
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.Title,
		arg.Description,
		arg.Score,
		arg.UserID,
		arg.ParkingLotID,
	)
	return err
}
