// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tests.sql

package database

import (
	"context"
)

const createTest = `-- name: CreateTest :one
INSERT INTO tests(id, name, created_at, updated_at) 
VALUES (
    gen_random_uuid(),
    'this is a test',
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTest(ctx context.Context) (Test, error) {
	row := q.db.QueryRowContext(ctx, createTest)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
