// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, name, email, hashed_password, role, parking_lot_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NULL,
    NOW(),
    NOW()
)
RETURNING id, name, email, role
`

type CreateUserParams struct {
	Name           string
	Email          string
	HashedPassword string
	Role           string
}

type CreateUserRow struct {
	ID    uuid.UUID
	Name  string
	Email string
	Role  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, hashed_password, role, parking_lot_id, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.HashedPassword,
			&i.Role,
			&i.ParkingLotID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFromEmail = `-- name: GetUserFromEmail :one
SELECT id, name, email, hashed_password, role, parking_lot_id, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserFromEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.ParkingLotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, name, email, hashed_password, role, parking_lot_id, created_at, updated_at FROM users
WHERE id  = $1
`

func (q *Queries) GetUserFromID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.ParkingLotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserParkingLot = `-- name: UpdateUserParkingLot :exec
UPDATE users
SET parking_lot_id = $1
WHERE id = $2
`

type UpdateUserParkingLotParams struct {
	ParkingLotID uuid.NullUUID
	ID           uuid.UUID
}

func (q *Queries) UpdateUserParkingLot(ctx context.Context, arg UpdateUserParkingLotParams) error {
	_, err := q.db.ExecContext(ctx, updateUserParkingLot, arg.ParkingLotID, arg.ID)
	return err
}
