// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getReviewsFromLotID = `-- name: GetReviewsFromLotID :many
SELECT userid, username, lotid, lotname, title, description, score, created_at, updated_at
FROM user_reviews_with_lot 
WHERE lotid = $1
`

func (q *Queries) GetReviewsFromLotID(ctx context.Context, lotid uuid.UUID) ([]UserReviewsWithLot, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsFromLotID, lotid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserReviewsWithLot
	for rows.Next() {
		var i UserReviewsWithLot
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Lotid,
			&i.Lotname,
			&i.Title,
			&i.Description,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
