// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAverageParkingTimeFromUserID = `-- name: GetAverageParkingTimeFromUserID :one
SELECT user_id, user_name, avg_minutes_parked
FROM avg_parking_time_per_user
WHERE user_id = $1
`

func (q *Queries) GetAverageParkingTimeFromUserID(ctx context.Context, userID uuid.UUID) (AvgParkingTimePerUser, error) {
	row := q.db.QueryRowContext(ctx, getAverageParkingTimeFromUserID, userID)
	var i AvgParkingTimePerUser
	err := row.Scan(&i.UserID, &i.UserName, &i.AvgMinutesParked)
	return i, err
}

const getCountOfLogsPerUser = `-- name: GetCountOfLogsPerUser :many
SELECT userid, username, totalentries
FROM count_of_logs_per_user
`

func (q *Queries) GetCountOfLogsPerUser(ctx context.Context) ([]CountOfLogsPerUser, error) {
	rows, err := q.db.QueryContext(ctx, getCountOfLogsPerUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOfLogsPerUser
	for rows.Next() {
		var i CountOfLogsPerUser
		if err := rows.Scan(&i.Userid, &i.Username, &i.Totalentries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestLowestRatingsFromUserID = `-- name: GetHighestLowestRatingsFromUserID :many
SELECT userid, username, lotid, lotname, title, description, score, created_at, updated_at, reviewtype
FROM user_highest_lowest_ratings
WHERE userid = $1
`

func (q *Queries) GetHighestLowestRatingsFromUserID(ctx context.Context, userid uuid.UUID) ([]UserHighestLowestRating, error) {
	rows, err := q.db.QueryContext(ctx, getHighestLowestRatingsFromUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserHighestLowestRating
	for rows.Next() {
		var i UserHighestLowestRating
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Lotid,
			&i.Lotname,
			&i.Title,
			&i.Description,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reviewtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsFromLotID = `-- name: GetReviewsFromLotID :many
SELECT userid, username, lotid, lotname, title, description, score, created_at, updated_at
FROM user_reviews_with_lot 
WHERE lotid = $1
`

func (q *Queries) GetReviewsFromLotID(ctx context.Context, lotid uuid.UUID) ([]UserReviewsWithLot, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsFromLotID, lotid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserReviewsWithLot
	for rows.Next() {
		var i UserReviewsWithLot
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Lotid,
			&i.Lotname,
			&i.Title,
			&i.Description,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRatedLots = `-- name: GetTopRatedLots :many
SELECT id, name, round
FROM top_rated_lot
`

func (q *Queries) GetTopRatedLots(ctx context.Context) ([]TopRatedLot, error) {
	rows, err := q.db.QueryContext(ctx, getTopRatedLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopRatedLot
	for rows.Next() {
		var i TopRatedLot
		if err := rows.Scan(&i.ID, &i.Name, &i.Round); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
